export const SET_CURRENT_USER = "SET_CURRENT_USER";


export const PUSH_ERROR = "PUSH_ERROR";
export const PUSH_ERROR_ARRAY = "PUSH_ERROR_ARRAY";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const REMOVE_ERROR = "REMOVE_ERROR";